### ISSUE TITLE
v1.3 Roadmap

### ISSUE THREAD

**Issue by Genteure** [Bililive/BililiveRecorder#164]
1.3 的主要功能已完成，可从 GitHub Actions 的 Artifacts 里下载使用。
在正式发布 1.3.0 之前还有一些细节需要修改调整，以及还需要再多测试一下新的录播修复系统。

---

v1.3 主要对项目里除界面以外的大部分逻辑进行重构重写，以实现

- 更好地调整和修复直播数据
- 添加一个修复工具页面用于修复其他录播软件录制的文件
- 能方便快捷地添加新的处理逻辑
- 能在录制同时更方便地提供更多更细的统计分析数据
- 解决现有的一些录制稳定性问题

当前进度

- [x] (95%) 重写数据处理
- [x] (95%) 重构录制逻辑
- [ ] (80%) 调整 WPF 和 CLI
  - [x] 使用新版 Core 的接口
  - [x] 添加修复工具页面
- [ ] (60%) 修改 CI Pipeline
  - [x] 使用 GitVersion 等方案生成版本号
  - [x] 迁移到 GitHub Actions
  - [ ] 修改新版本发布流程
